--  Create archive_card table

CREATE TABLE IF NOT EXISTS archive_card (
    id SERIAL PRIMARY KEY,
    number INT NOT NULL,
    title VARCHAR(255),
    flavor_text TEXT,
    effect TEXT,
    flipped_effect TEXT,
    in_codex BOOLEAN NOT NULL DEFAULT FALSE
);

-- Add Archive Cards to archive_card

INSERT INTO archive_card (id, number, title, flavor_text, effect, flipped_effect, in_codex)
SELECT * FROM (VALUES
    (1, 1, 'Outbreak', 'Windows are shut, curtains drawn, doors locked. Citizens hurry...', 'If a space has four or more doom, remove three doom from that space. Then place one doom in each other space in that neighborhood and one doom on the scenario sheet.', NULL, false),
    (2, 10, 'Fresh Meat', 'The steep gabled roofs of Arkham jut like teeth into the night sky...', 'When there are three or more clues on the scenario sheet, discard all clues from the scenario sheet and flip this card.', 'The leader gains Lita Chantler. Spawn the set-aside masked hunter engaged with the leader. Take cards 13 through 17 from the archive. Shuffle each card into the top two cards of the corresponding neighborhood deck. Place one marker facedown in each neighborhood. Add card 12 to the codex and return this card to the archive.', false),
    (3, 11, 'The Hunger Below', 'With every fog-haunted night...', 'When there is eight or more doom on the scenario sheet, flip this card.', 'If card 10 is still in the codex, flip that card before continuing. Take card 19 and spawn it at Hangmans Hill. Add card 18 to the codex and return this card to the archive.', false),
    (4, 12, 'False Faces', 'Between your own investigation and Lita Chantler...', 'After a worshiper of Umordhoth spawns, discard the marker in its neighborhood. After a worshiper is defeated, return that worshiper to the game box and place one marker on the scenario sheet. After the fifth marker is placed on the scenario sheet, if card 11 is still in the codex flip that card.', 'Investigators win the game!', false),
    (5, 13, 'Fresh Meat - Downtown', 'See Archive card 10 - Fresh Meat, flipped side.', 'Shuffle this card into top two cards of Downtosn neighborhood deck.', NULL, false),
    (6, 14, 'Fresh Meat - Easttown', 'See Archive card 10 - Fresh Meat, flipped side.', 'Shuffle this card into top two cards of Easttown neighborhood deck.', NULL, false),
    (7, 15, 'Fresh Meat - Rivertown', 'See Archive card 10 - Fresh Meat, flipped side.', 'Shuffle this card into top two cards of Rivertown neighborhood deck.', NULL, false),
    (8, 16, 'Fresh Meat - Uptown', 'See Archive card 10 - Fresh Meat, flipped side.', 'Shuffle this card into top two cards of Uptown neighborhood deck.', NULL, false),
    (9, 17, 'Fresh Meat - Southside', 'See Archive card 10 - Fresh Meat, flipped side.', 'Shuffle this card into top two cards of Southside neighborhood deck.', NULL, false),
    (10, 18, 'The Feast of Ghouls', 'The Reason for the mysterious disappearances stands revealed...', 'The Umordhoth epic monsters health is reduced by two for each marker on the scenario sheet. After the Umordhoth epic monster is defeated, flip card 12. When there is fifteen or more doom on the scenario sheet, flip this card.', 'Investigators lose the game.', false),
    (11, 19, 'Umordhoth', NULL, NULL, NULL, false)
);

--  Create encounter_card table

CREATE TABLE IF NOT EXISTS encounter_card (
    id SERIAL PRIMARY KEY,
    number VARCHAR(255),
    neighborhood VARCHAR(255),
    location1 VARCHAR(255),
    location2 VARCHAR(255),
    location3 VARCHAR(255),
    gameSet VARCHAR(255),
    location1Text TEXT,
    location2Text TEXT,
    location3Text TEXT
);

--  Add Encounter Cards for Easttown to encounter_card

INSERT INTO encounter_card (id, neighborhood, number, location1, location2, location3, location1Text, location2Text, location3Text, gameSet)
SELECT * FROM (VALUES
    (1, 'Easttown', '1/8', 'Hibb''s Roadhouse', 'Police Station', 'Velma''s Diner', 'You find yourself sitting with Old Man Hibbard at a corner table, watching the crowd ebb and flow on the dance floor in the old barn. He keeps pouring whiskey as long as you keep listening to him reminisce about the war in the Philippines. You or an ally recovers two sanity.', 'Sheriff Engle doesn''t seem to believe your stories about horrible monsters. Either test INFLUENCE to plead your case or spend one remnant to show him some proof. If you pass or spend the remnant, the sheriff gives you a gun and a badge; you become the DEPUTY OF ARKHAM and gain a SERVICE PIECE', 'Eggs over easy, hash browns, and Velma''s excellent coffee. You or an ally recovers two health. "Mind if I join you?" The man introduces himself as Ryan Dean, a traveling salesman. "Have I got a deal for you!" You may buy one COMMON item from the display for half prices (rounded up).', 'Core'),
    (2, 'Easttown', '2/8', 'Hibb''s Roadhouse', 'Police Station', 'Velma''s Diner', 'Joey "the Rat" Vigil whistles to catch your attention. "I''ve just, uh, come into possession of some merchandise. You interested?" You may buy one COMMON item from the display for half price (rounded up).', 'Deputy Dingby says you forgot something last time you were here, but you don''t recall doing so. Still, the deputy insists, so you pick through the lost and found anyway. You gain one COMMON item with value of three or less.', 'Velma makes you the best steak and potatoes you''ve ever tasted. You or an ally recovers two health. "One of my servers quit on me," says Velma. "Could you fill in for me?" Test INFLUENCE. If you pass, you become a SERVER AT VELMA''S. If you fail, you not-so-politely decline the offer.', 'Core'),
    (3, 'Easttown', '3/8', 'Hibb''s Roadhouse', 'Police Station', 'Velma''s Diner', 'As you''re about to enter the roadhouse, you hear the whinig of a hungry dog. You may spend $1 to get something for the mutt to eat and drink. If you do, the canine takes a liking to you and follows you as you leave; you or an ally recovers two sanity and a STRAY DOG joins you.', '"Tell me again what happened", says the desk sergeant. Either test OBSERVATION or spend one clue to recount the incident in vivid detail. If you pass or spend the clue, he looks the other way as you pick through the evidence locker; you gain one COMMON item with value four or greater.', 'Abner Weems, the local drunk, leans against the the wall as he starts telling you about the horrid fish-frog monster he saw at the docks until Velma shoos him away. "Git, you," She says, before turning to you with a sigh. "What''ll it be?" You may spend $1 for you or an ally to recover three health.', 'Core'),
    (4, 'Easttown', '4/8', 'Hibb''s Roadhouse', 'Police Station', 'Velma''s Diner', 'People don''t usually come here to read, but customers are welcome to read by the fire. You may spend $1 to get something to eat and drink. If you do, the simple human goodness of "Great Expectations" briefly restores your faith in humanity; you or an ally recovers three sanity.', 'A child tugs on your sleeve and asks you for help. "None of the officers will he me find Mrs. Flopsy (Test OBSERVATION)." If you pass, you find the missing rabbit and are the hero of the local children; you become BLESSED. If you fail, you search until it grows dark; you become DELAYED.', '"It''s some fancy vitamin drink," says Velma dubiously. "My supplier told me to try some, but I dunno. What do you think?" You may spend $1 to order some with your meal. If you do, you feel a new energy coursing through your veins; you or an ally recovers three health.', 'Core'),
    (5, 'Easttown', '5/8', 'Hibb''s Roadhouse', 'Police Station', 'Velma''s Diner', 'Everyone is wielding pool cues and broken bottles. Either test STRENGTH to join the brawl or spend $1 to order refreshments. If you pass or spend the money, it''s all a diverting amusement; you or an ally recovers three sanity. If you fail, you spend the night icing your bruised face; you suffer one damage.', 'An officer questions your involvement in the recent incident. You insist that he call his boss and mention your name (Test INFLUENCE). If you pass, the officer sheepishly hangs up the phone and politely asks you how he can help; you gain one COMMON item. If you fail, he tells you the sheriff has never heard of you.', 'The patron in the next booth is drawing some bizarre and disturbing icons in the margins of a newspaper. Either test OBSERVATION to covertly analyze the doodles or spend $1 to purchase the newspaper. If you pass or spend the money, the arcane images fortify your spirit against dark forces; you become BLESSED.', 'Core'),
    (6, 'Easttown', '6/8', 'Hibb''s Roadhouse', 'Police Station', 'Velma''s Diner', 'The singer''s tune comforts your troubled mind. You or an ally recovers two sanity. Her voice seems somehow hypnotic. You may spend $1 to stay a while longer. If you do, the melody fixes itself in your memory, bringing you good luck when you whistle the tune; you become BLESSED.', 'As you''re about to leave the station, Deputy Dingby stops you and accuses you of littering. Despite your protest that you didn''t drop anything, he forces something you''ve never seen before into your hands. "I seen you!" he says . "I seen you do it." You gain one COMMON item with value three or less', 'Velma serves up a Reuben that hits the spot. You or an ally recovers two health. A nurse is enjoying a slice of cherry pie. You may spend $1 to order a slice. If you do, you join her at the counter and she offers you some first aid for your wounds; you or an ally recovers two health.', 'Core'),
    (7, 'Easttown', '7/8', 'Hibb''s Roadhouse', 'Police Station', 'Velma''s Diner', 'You ask the gathered patrons if any of them have noticed the strange forces that have infected Arkham, but they all laugh and shake their heads. "You''ve had too much to drink," they tell you. Clearly you will find no allies here tonight. You may spend $1 for you or an ally to recover three sanity.', 'Trembling and bloody, an officer asks you if he has gone mad or if what he saw was real (Test INFLUENCE). If you pass, he hands ou the key to the armory and tells you to get ready for the fight; you gain one COMMON item with value four or greater.', 'You order a house specialty but ask for several alterations to the dish, requesting that particular spices be added and certain other ingredients be served on the side. The cook isn''t pleased, and Velma charges extra for all your fussing. You may spend $1 for you or an ally to recover three health.', 'Core'),
    (8, 'Easttown', '8/8', 'Hibb''s Roadhouse', 'Police Station', 'Velma''s Diner', 'A young couple buys you a drink to celebrate their recent engagement. You or an ally recovers two sanity. It is a welcome gift, but you can see they are clearly struggling for money. You may spend $1 to provide them with some cash as an engagement gift. If you do, you or an ally recovers two sanity.', 'A lunatic in handcuffs loudly boasts of future crimes. Spawn one clue. You relate what you know about the criminal (Test OBSERVATION). If you pass, the detective nods and tells an officer to "find something to keep this citizen safe;" you gain one COMMON item. If you fail, they hold you as well. You become DELAYED.', '"Sit," Velma insists as you stumble in through the door. She helps you to a table and fills a coffee cup for you. "You need a bowl of my stew. That''l fix you right up," she says. "Don''t worry, I''ll give you a discount. I like your face." You may spend $1 for you or an ally to recover three health.', 'Core')
);

--  Add Encounter Cards for Rivertown to encounter_card

INSERT INTO encounter_card (id, neighborhood, number, location1, location2, location3, location1Text, location2Text, location3Text, gameSet)
SELECT * FROM (VALUES
    (9, 'Rivertown', '1/8', 'Black Cave', 'General Store', 'Graveyard', 'You trace your fingers along the pictographs on the cave wall (Test LORE). If you pass, fragments of a secret history blossom like a garden in your brain; you gain one spell. If you fail, your mind reels at the terrible history you see; you suffer one horror.', 'You swap some boasts and tall tales with Mr. Hatle and the other old geezers playing checkers by the potbellied stove. Eventually, Davy Schoffner comes over and asks if you''re planning to buy anything or if you''d all kindly be quiet and leave. You may buy any number of common items from the display.', 'You whistle as you walk by the graveyard. Maybe it''s superstitious, but you always feel it brings you luck. When you''re past the graveyard and you stop your whistling, you find a shiny penny in your path. You become BLESSED.', 'Core'),
    (10, 'Rivertown', '2/8', 'Black Cave', 'General Store', 'Graveyard', 'The stone tablets are too heavy to move. You''ll have to read them here. You gain one spell. The tide is coming in and the water laps at your ankles (Test WILLPOWER). If you pass, you hold your breath and swim out of the cave. If you fail, the undertow dashes you against the rocks; you suffer two damage.', 'A bedraggled gray tabby eyes you with suspicion from the alley nearby. Either test INFLUENCE to pretend to ignore the cat or spend $1 to coax it out with fresh fish. If you pass or spend the money, the feline takes an interest; the STRAY CAT joins you. If you fail ,the feline is wise to your tricks and ignores you harder.', 'You kick at the rats, trying to uncover what the horrid swarm is so interested in (Test STRENGTH). If you pass, you drive the vermin away and turn your attention to the alien creature they were gnawing on; you gain one remnant. If you fail, the rats bite and gnaw at your legs; you suffer one damage.', 'Core'),
    (11, 'Rivertown', '3/8', 'Black Cave', 'General Store', 'Graveyard', 'You hide in the shadows and watch the robed figures incant their strange ritual. You gain one spell. The magic seems to flow through you (Test WILLPOWER). If you pass, you resist the effects and ward the area; you remove one doom from any space in your neighborhood. If you fail, you become CURSED.', 'Schoffner''s General is busy today. You may buy any number of COMMON items from the display. As you''re leaving, Nathan is loading up the truck to make a few deliveries. You may help him. If you do, he offers to give you a ride; you may move up to three spaces.', 'Someone grabs you from behind! You struggle with your attacker, hardly able to see them in the moonless night (Test STRENGTH). If you pass, they run away, leaving their torn coat pocket and wallet in your hand; you gain $3. If you fail, you catch a brief glimpse of their alien face; you suffer one horror.', 'Core'),
    (12, 'Rivertown', '4/8', 'Black Cave', 'General Store', 'Graveyard', 'You find a water-logged journal that must belong to the Sheldon gang. It appears to be written in some sort of code (Test LORE). If you pass, you break the cipher and discover a hidden cache of smuggled goods; you gain the CONTRABAND WHISKEY. If you fail, you''re sure it is meant to lead you, but where?', 'You bang on the door again. "Hold your horses!" shouts the owner, Davy Schoffner, from inside. "You know what time it is? Just let me get my drawers on." After a moment, the door opens and you rush inside. You may buy any number of COMMON items from the display.', 'The groundskeeper Leonard Coburn asks you to help dig a fresh grave. Either test STRENGTH to get the job done quickly or become delayed to take your time. If you pass or become delayed, you uncover something strange; you gain one remnant and $3. If you fail, you wear yourself out and collapse.', 'Core'),
    (13, 'Rivertown', '5/8', 'Black Cave', 'General Store', 'Graveyard', 'Spurs of rock surround the passageway like a toothy maw. You steel yourself to enter (Test WILLPOWER). If you pass, you discover wax and chalk markings that suggest a ritual was held here and find something that was left behind; you gain one CURIO item. If you fail you retreat in fear; you suffer one horror.', 'The storm clouds part and a shaft of golden sunlight spills down upon you. The smell of the rain and warmth of the sun make you feel invincible. You become BLESSED. "Flash sale! Everything half off!" shouts Davy Schoffner. You may buy one COMMON item from the display for half price (rounded up).', 'The hairs on your neck stand on end (Test WILLPOWER). If you pass, you communicate with a lonely ghost who directs you to tarnished silver coins and urges you to spend them well; you gain $3. If you fail, the icy feeling of being watched follows you no matter how fast you flee; you suffer two horror.', 'Core'),
    (14, 'Rivertown', '6/8', 'Black Cave', 'General Store', 'Graveyard', 'An elaborate mosaic made of shells, glass, and tiles depicts a profane image of a toad-like monstrosity. You may become delayed to painstakingly remove the picture piece by piece. If you do, you feel as if the oppressive sense of foulness that once permeated the cave has been reduced; you become BLESSED.', 'You notice the rifle that usually hangs on the wall has gone missing. "I''ve got it loaded behind the counter," says Davy. "We''ve been getting a lot of dangerous oddballs coming around, but don''t worry. We plan on staying open." You may buy any number of COMMON items from the display.', 'The darkness and fog make you wish you hadn''t agreed to dig these graves. Suddenly, something cold and wet touches the back of your leg (Test WILLPOWER). If you pass, it''s just a friendly dog with a wallet in its mouth; you gain $3. If you fail, you run screaming into the night; you suffer one horror.', 'Core'),
    (15, 'Rivertown', '7/8', 'Black Cave', 'General Store', 'Graveyard', 'The blackness around you is watching and listening. Either test WILLPOWER to steel your mind and stare down the darkness or spend one remnant to appease it. If you pass or spend the remnant, the darkness flows into your mind; you gain one spell. If you fail, the pitiless blackness drives you back toward the light.', 'The owner is busy with another customer. Nathan, the delivery boy, walks up to you . "If you give me a list of the things you need," he mumbles, "I can see what we have and ring you up." He searches his apron pockets for a pencil. You may buy any number of COMMON items from the display.', 'A canine figure lurks by an open grave, gnawing on a severed limb. You loose a mighty roar (Test WILLPOWER). If you pass, the ghoul flees and leaves behind the remains of its meal; you gain one remnant. If you fail, the ghoul howls and knocks you down before escaping into the dark; you suffer one horror.', 'Core'),
    (16, 'Rivertown', '8/8', 'Black Cave', 'General Store', 'Graveyard', 'According to local legend, a witch once lived in these caves. Either test LORE to remember the exact location or spend one clue to check your notes. If you pass or spend the clue, you discover old, broken trinkets; you gain one CURIO item. If you fail, you hear the whispers of an old woman in the cave.', 'Davy Schoffner, the owner, waves his pencil in the air, taking a mental tally of his wares. "Inventory time," he tells you. "Please buy something. I''ve put it all on sale. I don''t want to be here all night counting it." You may buy one COMMON item from the display for half price (rounded up).', 'As you enter, you notice a sign on the gatehouse indicating that the groundskeeper Leonard Coburn is hiring a gravedigger. You may apply for the position. If you do, you become a GRAVEDIGGER. If you don''t, you enjoy your leisurely stroll through the graveyard; you or an ally recovers one sanity.', 'Core')
);

--  Add Encounter Cards for Uptown to encounter_card

INSERT INTO encounter_card (id, neighborhood, number, location1, location2, location3, location1Text, location2Text, location3Text, gameSet)
SELECT * FROM (VALUES
    (17, 'Uptown', '1/8', 'Hangman''s Hill', 'St. Mary''s Hospital', 'Ye Olde Magick Shoppe', 'A woman lights candles all throughout the old graveyard, but only criminals and witches are interred here (text WILLPOWER). If you pass, you befriend the woman and she explains her grandmother was a witch; DAYANA ESPERENCE joins you and you gain one remnant. If you fail, you avoid the place.', 'Looking furtively left and right, the orderly opens the glass case and takes out a small bottle of painkillers. You or an ally recovers two health. "Any more and you gotta pay. I''m not running a charity here." You may spend $1 for you or an ally to recover two health.', '"That''s enough browsing!" Startled, you jerk up to see Miriam Beecher, the proprietor, at your shoulder. "If you''re not buying, then get out!" Reveal the top three spells in the deck. You may buy one of them for half price (rounded up). Put the rest on the bottom of the deck.', 'Core'),
    (18, 'Uptown', '2/8', 'Hangman''s Hill', 'St. Mary''s Hospital', 'Ye Olde Magick Shoppe', 'You find a trapdoor under the moldering runner in the decaying church, but it''s warped and stuck shut (Test STRENGTH).  If you pass, you discover laboratory equipment in a secret basement and the remains of some strange creature; you gain one remnant. If you fail, whatever''s under there will remain a mystery.', '"Please wait your turn," says Nurse Sharon. "There are a lot of patients ahead of you." Either test INFLUENCE to put on your best smile or spend $1 to make yourself a priority. If you pass or spend the money, she agrees to see you now; you or an ally recovers three health. If you fail, you don''t have time to wait.', 'You see a familiar-looking old book and unfold the blood-spattered page from your pocket. The markings in the margins match. You may spend $3 to purchase the rare text. If you do, you align the torn edge along the book''s inner spine and read the writing in its entirety; you become BLESSED.', 'Core'),
    (19, 'Uptown', '3/8', 'Hangman''s Hill', 'St. Mary''s Hospital', 'Ye Olde Magick Shoppe', 'A coven of witches has gathered in the woods, performing some sort of occult ritual. You try to keep calm (Test WILLPOWER). If you pass, you observe them from the shadows and steal some ritual components; you gain one spell and one remnant. If you fail, they hear your gasps of dismay; you become CURSED.', 'Nurse Sharon is quick and efficient, if not precisely gentle. You or an ally recovers two health. Either test INFLUENCE to request some painkillers or spend $1 to buy them outright. If you pass or spend the money, Doctor Mortimore writes you a prescription for some morphine; you or an ally recovers two health.', 'A sleek black cat rubs against your leg. The BLACK CAT joins you. "That''s no normal feline," says Miriam Beecher. Either test LORE to show her you''re no normal human or spend $2 to pay for her advice. If you pass or spend the money, Miriam and the cat teach you a charm; you gain one spell.', 'Core'),
    (20, 'Uptown', '4/8', 'Hangman''s Hill', 'St. Mary''s Hospital', 'Ye Olde Magick Shoppe', '"It fell off a truck, you get me?" explains Joey Vigil. "You buying or what?" Either test STRENGTH to extort him or spend $3 to buy. If you pass or spend the money, Joey "the Rat" leaves you with your new property; you gain one COMMON item. If you fail, Joey''s tougher than he looks; you suffer one damage.', '"Well you''re just covered in bumps and bruises, honey," notes Doctor Maheswaren. You or an ally recovers two health. "What have you been up to?" You may spend one clue or one remnant to tell her. If you do, she shares what she''s experienced; place one clue from the clue pool on the scenario sheet.', '"These books were owned by the Comte de Saint Germain himself," explains Miriam Beecher. "So you know I cant''t let em go cheap." Reveal the top four spells in the deck. You may buy any number of them. Put the rest on the bottom of the deck.', 'Core'),
    (21, 'Uptown', '5/8', 'Hangman''s Hill', 'St. Mary''s Hospital', 'Ye Olde Magick Shoppe', 'Recent rains have washed up an old coffin. You steel yourself and pry it open (Test WILLPOWER). If you pass, the body within isn''t human and something was buried with it; you gain one COMMON item and one remnant. If you fail, the corpse''s sightless eye sockets stare into your soul; you suffer one horror.', 'Nurse Sharon calls your name. "It''s been a pretty quiet day. We''ll have you fixed up and out the door in no time." After Doctor Mortimore examines you, he recommends a few quick and inexpensive procedures. You may spend $1 for you or an ally to recover three health.', 'Miriam Beecher agrees to teach you meditation exercises. You focus (FOCUS a skill) even if it exceeds your focus limit. "That was just a taste," she says. "I charge for the advanced classes." Reveal the top three spells in the deck. You may buy one of them. Then put the rest on the bottom of the deck.', 'Core'),
    (22, 'Uptown', '6/8', 'Hangman''s Hill', 'St. Mary''s Hospital', 'Ye Olde Magick Shoppe', 'You see something on the bank of Hangman''s Brook. You gain one COMMON item. You wade into the water looking for more (Test WILLPOWER). If you pass, you find something strange wrapped in oilskin; you gain one remnant. If you fail, you find nothing before the cold water forces you to abandon your search.', 'The hospital is too busy and none of the regular doctors or nurses have any time for you. An old Chinese man proposes acupuncture. You may spend $2 to have him stick you with needles. If you do, it doesn''t do anything for your wounds but you feel surprisingly refreshed; you become BLESSED.', 'The proprietor Miriam Beecher motions to you. "For a real aficionado like yourself, I keep a special collection of our rarest offerings in the back room. Care for a look?" Reveal the top four spells in the deck. You may buy any number of them. Put the rest on the bottom of the deck.', 'Core'),
    (23, 'Uptown', '7/8', 'Hangman''s Hill', 'St. Mary''s Hospital', 'Ye Olde Magick Shoppe', 'You wait until the Sheldon Gang''s thugs leave before sneaking in to pry open a crate (Test STRENGTH). If you pass, it seems the rum-runners are smuggling more than just rum; you gain one COMMON item. If you fail, you take too long and the Sheldon Gang returns to rough you up; you suffer two damage.', 'While you are waiting, you visit the hopital''s cafeteria. Once you smell the food you realize how long it has been since you had a real meal. Maybe all you really need is something to eat. You may spend $1 for you or an ally to recover three health.', '"You''re in luck," Miriam Beecher tells you. "I just got this box of books from a collector in Boston. I haven''t had a chance to sort it yet. Have a look and make me an offer!" Reveal the top three spells in the deck. You may buy any number of them. Put the rest on the bottom of the deck.', 'Core'),
    (24, 'Uptown', '8/8', 'Hangman''s Hill', 'St. Mary''s Hospital', 'Ye Olde Magick Shoppe', 'A haggard man is sitting on the hill, eating the petals of witchweed flowers. He laughs when he sees you and says, "Tell me a story or listen to mine. Show me a marvel, my good fortune''s thine." You may spend one focus to play along. If you do, he tells you terrifying truths; you become BLESSED.', 'Doctor Maheswaren looks over the results. "It could be something serious. You''re in luck, though. We''ve just begun a trial of a new serum that has been working wonders." Joining the trial is expensive, but Maheswaren is very enthusiastic about the results. You may spend $2 to gain the MYSTERIOUS SERUM.', 'The book calls to you, and when you touch it the knowledge within rushes into your mind like a living thing. You gain one spell. Your mind staggers as it attempts to absorb this new cosmic understanding (Test WILLPOWER). If you fail, you feel as if the spell is an alien intelligence; you suffer two horror.', 'Core')
);

--  Add Encounter Cards for Downtown to encounter_card

INSERT INTO encounter_card (id, neighborhood, number, location1, location2, location3, location1Text, location2Text, location3Text, gameSet)
SELECT * FROM (VALUES
    (25, 'Downtown', '1/8', 'Arkham Asylum', 'Independence Square', 'La Bella Luna', 'You check yourself into the asylum. You recover two sanity. You befriend one of the other patients, who mumbles about cursed oaths and powers beyond the mortal. You decide to sneak him out (Test OBSERVATION). If you pass, DANIEL CHESTERFIELD joins you. If you fail, you are caught and forced to leave.', '"You must allow me to read your future!" insists the fortune teller Anna Kaslow. She flips several tarot cards as you sit. "The darkness that falls over Arkham is watching you closely. Be ready to act. Seize any opportunity." She gives you a card to keep as a talisman. You gain the ACE OF RODS.', 'The Clover Club beneath La Bella Luna is the best place to gamble away your hard-earned cash. "Pass-line bet for our friend here," says the croupier. "Roll ''em!" Roll two dice. On a 7 or 11, you double your bet; you gain $5. On a 2, 3, or 12, you lose the bet and top out the croupier; you discard $3.', 'Core'),
    (26, 'Downtown', '2/8', 'Arkham Asylum', 'Independence Square', 'La Bella Luna', 'The formidable Nurse Heather is not convinced that you require psychiatric treatment. You may spend $1 to help her past her misgivings. If you do, she not only checks you in for treatment but offers one of her vigorous, nearly painful massages; you or an ally recovers three sanity.', 'You follow the sounds of music and children laughing to the bandstand, but no one is there (Test WILLPOWER). If you pass, you feel as though you were meant to find this; you gain one CURIO item. If you fail, you find only a small rusted toy cornet of the type you played with as a child; you suffer one horror.', 'You don''t know what you did to insult the guy, but the next thing you know you''re getting a wine bottle cracked across your phiz. "Hey!" someone shouts. "How about you pick on someone your own size!" Soon you both land face down in the street. You suffer two damage and gain one ally.', 'Core'),
    (27, 'Downtown', '3/8', 'Arkham Asylum', 'Independence Square', 'La Bella Luna', '"Sure, you could waste your time talking to the doctors every week," suggests the orderly. "Or maybe just take a snootful of this." After checking that no doctors are around to observe, he holds out a small square of folded paper. You may spend $1 for you or an ally to recover three sanity.', 'A flea market has sprung up, filling the square with happy voices and colorful wares. You browse the stalls in something of a daze, hoping to take your mind off the terrible things you have seen. You may buy any number of COMMON items from the display.', 'The goon doesn''t want to let you into the Clover Club beneath the restaurant. You tell him you''re here to see Naomi O''Bannion (Test INFLUENCE). If you pass, a few games at the card tables let you turn a profit; you gain $3. If you fail, Naomi must not be accepting visitors right now; you suffer one damage.', 'Core'),
    (28, 'Downtown', '4/8', 'Arkham Asylum', 'Independence Square', 'La Bella Luna', '"You must be one of the candidates for the trial," says Nurse Heather. You may spend $1 to pay the fee. If you do, Doctor Mintz appears at your side and injects you with something before you can object; you focus two skills of your choice, even if it exceeds your focus limit', 'A rag-and-bone man pushes his cart across the square (Test WILLPOWER). If you pass, you chat for a moment and he gives you a token of appreciation; you gain one COMMON item. If you fail, when you turn to speak with him there is nothing but a pile of stinking rags and rotting driftwood; you suffer one horror.', 'Peter Clover, the proprietor of the Clover Club beneath the restaurant, lays a meaty hand on your shoulder. "They say you''re pretty good with the numbers (Test OBSERVATION)." If you pass, you''re paid well for cooking the books; you gain $3. If you fail, Peter isn''t pleased; you suffer two damage.', 'Core'),
    (29, 'Downtown', '5/8', 'Arkham Asylum', 'Independence Square', 'La Bella Luna', 'You speak briefly with Charles Badoe, the chief psychiatrist. You or an ally recovers two sanity. Either test INFLUENCE to convince him to devote more time or spend $1 to pay his fee. if you pass or spend the money, Charles devotes his full attention to your concerns; you or an ally recovers two sanity.', 'A band of Romani nomads have settled in the square for the moment. Some sing adn dance, while others offer jewelry and other trinkets for sale. You may buy one CURIO item from the display for half price (rounded up).', 'A panicked stranger forces a wad of cash into your hand. You gain $3. This benefactor tells you, "You gotta get me outta here," and points to the club''s imposing bouncer (Test OBSERVATION). If you pass, you stealthily escort the stranger to safety. If you fail, you both get caught; you suffer two damage.', 'Core'),
    (30, 'Downtown', '6/8', 'Arkham Asylum', 'Independence Square', 'La Bella Luna', 'An epidemic of trauma and madness has swept the city, and the asylum is overwhelmed by desperate souls seeking help. You may spend $1 to bribe a staff member. If you do, you are given priority and prescribed a highly effective medication; you or an ally recovers three sanity.', 'Anna Kaslow, the old soothsayer, is offering tarot readings. You may spend $1 to have her tell your fortune. If you do, the cards reveal that many challenges await you in the future, but you will triumph if you believe in yourself and trust your intuition; you gain THE MOON.', 'A desperate gambler pleads for a line of credit. You offer to vouch for the stranger (Test INFLUENCE). If you pass, the grateful stranger shares his winnings and you feel inspired; you gain $3 and become BLESSED. If you fail, the pit boss holds you responsible for the gambler''s loss; you discard $2.', 'Core'),
    (31, 'Downtown', '7/8', 'Arkham Asylum', 'Independence Square', 'La Bella Luna', 'Charles Badoe, the chief psychiatrist, is running a trial of a new experimental "dream enhancer." You may spend $2 to take part in the trial. If you do, you dream of a beautiful city where humans and cats live in harmony and every day is peaceful; you recover three sanity and become BLESSED.', 'A poor Dunwich family has parked their truck by the square and are selling old furniture and knick-knacks out of the back. Most of what they have for sale is worn out and worthless, but a few objects look worthwhile. You may buy one COMMON item from the display for half off (rounded up).', 'You join a hand of blackjack at the Clover Club beneath La Bella Luna. No one''s noticed yet that you''ve been counting cards (Test OBSERVATION). If you pass, your deception pays off; you gain $3. If you fail, the pit boss catches on and has you taken out back for a lesson. You suffer two damage.', 'Core'),
    (32, 'Downtown', '8/8', 'Arkham Asylum', 'Independence Square', 'La Bella Luna', 'While in the waiting room, you doze off and get some badly needed sleep. You or an ally recovers two sanity. You feel refreshed when you are awakened by Nurse Heather calling your name. She says the doctor is ready to see you. You may spend $1 for you or an ally to recover two sanity.', 'You sit with the soothsayer Anna Kaslow, and she teaches you how to cast runes to predict your future. You hold a question in your mind as you select runes from a bag (Test WILLPOWER). If you pass, you see your path to success; you become BLESSED. If you fail, the runes promise destruction; you suffer one horror.', 'In the VIP area of the Clover Club beneath the restaurant, Peter Clover winks and pins a four-leaf clover to your coat. You become a CLOVER CLUB MEMBER. "Do me a favor in return someday." You offer to pull some strings on his behalf (Test INFLUENCE). If you pass, he pays you in advance; you gain $3.', 'Core')
);

--  Add Encounter Cards for Southside to encounter_card

INSERT INTO encounter_card (id, neighborhood, number, location1, location2, location3, location1Text, location2Text, location3Text, gameSet)
SELECT * FROM (VALUES
    (33, 'Southside', '1/8', 'Historical Society', 'Ma''s Boarding House', 'South Church', 'As you explore the library, you find genealogical records of your own family. You may spend one remnant to compare the documents to your findings. If you do, you trace your lineage to the Marsh family of Innsmouth; you suffer one direct horror and gain the INNSMOUTH LOOK.', 'Body and mind heavy as lead, you collapse on the couch--you''re asleep before you can pay for a room. You or an ally recovers two health. Ma shows mercy and lets you sleep for a couple of hours before waking you, not unkindly, and sending you on your way. You move to an adjacent street and become delayed.', 'You sit in the silence of the nearly empty church. The building feels like a safe haven, despite the crumbling walls and cracked pews. You may spend $1 to donate to the church''s repair costs. If you do, you feel better knowing you have somewhere to return to; you or an ally recovers three sanity.', 'Core'),
    (34, 'Southside', '2/8', 'Historical Society', 'Ma''s Boarding House', 'South Church', 'The dejected curator writes "canceled" on the placard advertising tonight''s guest speaker. Either test INFLUENCE to offer to replace the speaker or spend one remnant to donate your finding for discussion. If you pass or spend the remnant, someone you speak with is moved by your speech; you gain one ally.', 'You arrive just in time for dinner. Ma places the heaping plate of roast beef, carrots, and potatoes in front of you and wipes her hands on her apron. You or an ally recovers two health. "Second helping, deary?" asks Ma, holding another plate. You may spend $1 for you or an ally to recover two health.', 'You step into the hush of the confessional and release a sigh. "What''s troubling you, my child?" asks the kindly voice of Father Michael. All of your fears come tumbling out of you. Father Michael assures you that your path is true and just. You recover two sanity and become BLESSED.', 'Core'),
    (35, 'Southside', '3/8', 'Historical Society', 'Ma''s Boarding House', 'South Church', 'You browse the collection of the historical society and comment about a particular piece that stands out to you. "Why, this isn''t part of the collection," says the curator Mr. Peabody. "How did this get here? I suppose you''d better take it with you." You gain one CURIO item.', '"Join me for a taste?" asks "Jazz" Mulligan, the head janitor from Miskatonic University, as Ma sets out a fresh apple pie. "Oops, I think I forgot my wallet." You may spend $1 to pay for his share. If you do, you share a companionable evening eating pie and chatting; you or an ally recovers three health.', 'You step into the hush of the confessional and release a sigh. An unnatural darkness clings to the chamber, and a sinister rattling voice whispers to you from behind the curtain, "The power you seek is yours for the taking." You may gain a DARK PACT condition to gain a DARK BLESSING.', 'Core'),
    (36, 'Southside', '4/8', 'Historical Society', 'Ma''s Boarding House', 'South Church', 'You ask the curator, Mr. Peabody, to let you borrow something from the society''s collection (Test INFLUENCE). If you pass, he grants your request, "but be careful with it, if you please;" you gain one CURIO item. If you fail, Mr. Peabody explains, at length, that these items are of historical value and aren''t for your use.', 'A short rest at Ma''s is just what you need. You may spend $1 for you or an ally to recover three health. Ma tells you about a hunter who stayed with her but vanished in the night. That was weeks ago, and now Ma is looking for someone to take care of the man''s dog. The HUNTING DOG joins you.', 'J. S. Bach was a devout Protestant, but the Catholics don''t seem to be holding that against him. The majestic chords of his Mass in B Minor echo through the church. You allow the melody to flow through you and carry away your worries and fears. You or an ally recovers two sanity.', 'Core'),
    (37, 'Southside', '5/8', 'Historical Society', 'Ma''s Boarding House', 'South Church', 'Carl Sanford, the leader of the Silver Twilight Lodge, says he foresees great things in your future. You become BLESSED. He mentions that the "strange happenings" in Arkham worry him. You may spend one remnant to share your own concerns. If you do, Sanford arranges an introduction; you gain one ally.', 'The storm has knocked out the power, but you pass the evening by Ma''s fireplace and feel renewed. You or an ally recovers two health. The howling wind has a way of creeping into the boarding house, but Ma''s homemade stew will warm you right up. You may spend $1 for you or an ally to recover two health.', 'The church is filled with people who are terrified and devastated. You may spend $1 to help provide food and shelter for those who have lost everything due to the dark forces roaming the streets of Arkham. If you do, you see hope for the city''s recovery; you or an ally recovers three sanity.', 'Core'),
    (38, 'Southside', '6/8', 'Historical Society', 'Ma''s Boarding House', 'South Church', 'Another guest of the society is fascinated by one of the displays describing Arkham''s witch trials (Test INFLUENCE). If you pass, you strike up a friendly conversation and discover you share a cause; you gain one ally. If you fail, your attempts at joviality backfire and the guest leaves in a huff.', 'A guest damaged some antique furniture. Either test INFLUENCE to assuage Ma''s wrath or spend $3 to pay for the repairs. If you pass or spend the money, the apologetic guest asks if you need any help; you gain one ally. If you fail, Ma''s wrath turns on you as well; move to an adjacent street.', 'Father Michael asks you to contribute toward a dinner provided for the poor and homeless. You may spend $1 to help pay for groceries. If you do, you spend the evening serving food and sharing a pleasant meal with Arkham''s less fortunate; you or an ally recovers three sanity.', 'Core'),
    (39, 'Southside', '7/8', 'Historical Society', 'Ma''s Boarding House', 'South Church', 'Only donating members of the society have access to several of the museum''s exhibits. You may spend one remnant to donate your findings. If you do, you study a map of Arkham with strange markings and find something that has been abandoned under the table; you gain one CURIO item and spawn one clue.', 'One of the guests introduces himself as a "Sawbones," and explains that he was a medic during the Great War. After a rambling story about the horrors he saw there, he offers to help you if you''ll just buy him a little something to keep his hands steady. You may spend $1 for you or an ally to recover three health.', 'The church is filled with inspirational artwork and you get so engrossed that you are unaware of how late it has become. You recover four sanity and become delayed. The church bell pulls you from your reverie (Test WILLPOWER). If you pass, you resolve to preserve this beauty; you focus one skill of your choice.', 'Core'),
    (40, 'Southside', '8/8', 'Historical Society', 'Ma''s Boarding House', 'South Church', 'All of the tickets to tonight''s event have been sold. Either test INFLUENCE to convince the doorman that you''re a guest speaker or spend $3 to buy someone''s ticket. If you pass or spend the money, the exhibit features several oddities from Arkham''s storied past; you gain one CURIO item.', 'Ryan Dean, a traveling salesman, proffers a bottle of his "cure-all tonic." "The stuff works wonders, but it''s not cheap!" You may spend $2 to pay what he''s asking. If you spend the money, you find the medicine has a foul taste but it works miracles; you recover three health and become BLESSED.', 'A missionary has returned to tell stories of her travels in the remotest parts of the world. You man spend $1 to support her ongoing work. If you do, she gratefully shares a traditional charm for good luck; you or an ally recovers three sanity.', 'Core')
);

--  Add Encounter Cards for The Streets to encounter_card

INSERT INTO encounter_card (id, neighborhood, number, location1, location2, location3, location1Text, location2Text, location3Text, gameSet)
SELECT * FROM (VALUES
    (41, 'The Streets', '1/8', 'Residential', 'Bridge', 'Scenic', 'Joey Vigil''s sharp whistle catches your attention from a nearby alley. "I know you need a little help and can''t afford to ask too many questions," he says, "so I got a special deal for you." You may buy one COMMON item from the display for half price (rounded up).', 'A leathery old man stands against the rail in the center of the river, fishing rod in hand and a bucket of crushed ice at his feet. Seeing you, he nods and, in traditional laconic New England fashion, offers you a cold beer and a rest. You may become delayed for you or an ally to recover two sanity.', 'Something rustles through the bushes to your right. It''s probably nothing, and you struggle to keep calm (Test WILLPOWER). If you pass, a friendly dog bursts from the leaves and demands affection; you or an ally recovers three sanity. If you fail, the rustling becomes cracking and crashing and you run for it.', 'Core'),
    (42, 'The Streets', '2/8', 'Residential', 'Bridge', 'Scenic', 'Abner Weems, the local drunk, staggers in front of you and grabs your lapels. "My wife," he moans, "my daughter. I miss them so." He presses his face against you and sobs, leaving you damp and smelly. You may become delayed to comfort him. If you do, he''s grateful; you gain one CURIO item.', 'Nathan, the delivery boy from Schoffner''s General Store, walks past you with a hand-truck, and something falls from the stack of boxes. You may return the goods. If you do, he thanks you profusely; gain $1 and recover one health and one sanity. Otherwise, you gain one COMMON item.', 'You come across a park bench beneath a stand of birch trees, their leaves golden in the setting sun. You sit and enjoy a few quiet moments of birdsong, warmth, and peace. You or an ally recovers one health and one sanity.', 'Core'),
    (43, 'The Streets', '3/8', 'Residential', 'Bridge', 'Scenic', 'Ryan Dean stands on the bed of an old truck, talking up the efficacy of his latest product to a crowd of locals (Test INFLUENCE). If you pass, you see through his con and he slips you a few bills to keep you quiet; you gain $2. If you fail, you buy a bottle of Clark Stanley''s Snake Oil Liniment; you discard $2.', 'Abner Weems, the town drunk, is leaning over the edge of the bridge, and for a moment it seems he might jump (Test INFLUENCE). If you pass, Abner reveals that he was just fetching something he spotted on the edge of the bridge; you gain one COMMON item. If you fail, Abner cusses you out and staggers off.', 'Something glimmers in the shadows beneath the trees (Test OBSERVATION). If you pass, you find a small cache of shiny rocks and coins, presumably stashed by a crow or rodent; you gain $2. If you fail, you pause to look but can''t see anything of interest from the path aside from a small passing deer."', 'Core'),
    (44, 'The Streets', '4/8', 'Residential', 'Bridge', 'Scenic', 'The grim clouds and dim light match your mood as you trudge through Arkham''s streets. The empty windows and doorways around you seem to stare, mocking your confusion and your quest, but then a shining coin catches your eye. You gain $1. Walking more easily now, you continue on.', 'You can''t find the source of the persistent "psst!" at first, until you think to look under the bridge where a disheveled-looking Joey "the Rat" Vigil is skulking. "I need to raise some funds and quick," he says. You may buy one COMMON item from the display for half price (rounded up).', 'You hear a cry for help--a robed figure with a curved knife is assaulting some poor innocent person (Test STRENGTH)! If you pass, you drive the assailant away to the grateful praise of your new best friend for life; gain one ally. If you fail, you are too late to prevent another of Arkham''s mysterious murders.', 'Core'),
    (45, 'The Streets', '5/8', 'Residential', 'Bridge', 'Scenic', 'An old woman startles you from your reverie and begs your help to cross the street. She chatters about her grandchildren all the way to the other side. Her ignorance of the darkness you fight is somehow reassuring. You or an ally recovers one sanity, and you focus one skill of your choice.', 'From your vantage point, you can see a flock of gulls arguing loudly over something at the edge of the water (Test OBSERVATION). If you pass, you discover that their prize is the corpse of a robed figure, which you quickly search; you gain one remnant. If you fail, it''s probably just a flock of gulls being gulls.', 'A tremendous old apple tree leans over the gravel road, its limbs heavy with round, red fruit. You help yourself to a particularly fine-looking apple; you or an ally recovers two health. After a few bites, it''s clear that the apple is a little shy of ripe and the tartness makes your lips pucker, but you finish it anyway.', 'Core'),
    (46, 'The Streets', '6/8', 'Residential', 'Bridge', 'Scenic', 'You remember a shortcut near here (Test OBSERVATION). If you pass, you duck along an alley and cut a full block from your route; you may move up to two spaces, ignoring monsters during this movement. If you fail, you double back after you spot a monster; spawn one monster in your space and exhaust it.', 'A truck rambles by, loaded with newspapers outbound from the Arkham Advertiser. The truck hits a bump and one paper tumbles free. It is immediately caught by the wind and blows past you (Test OBSERVATION). If you pass, you snatch the paper and read it carefully; spawn one clue.', 'Something has been carved into the bank of a tree (Test LORE). If you pass, you recognize the proud declaration of youthful love some twenty years gone in the scars on the tree bark; you or an ally recovers two sanity. If you fail, the evidence of widespread and persistent cult activity makes you shudder.', 'Core'),
    (47, 'The Streets', '7/8', 'Residential', 'Bridge', 'Scenic', '"Stop right there!" A figure rushes past you with Deputy Dingby hot on the trail (Test OBSERVATION). If you pass, you see where the thief stashes their loot; you gain one COMMON item. If you fail, Dingby arrests you while you argue that you look nothing like the thief; you become delayed.', 'Andre Hopkins is pushing his cart past you and the smell of roasting peanuts makes your mouth water. "Want something?" He asks you. "I still got some left." You may spend $1 for you or an ally to recover three health.', 'The rustling of the leaves around you seems to be the whispers of an unknown god, something that dwelt here before the coming of mankind, something that will dwell here still long after mankind is gone. You scurry on, eager to get away from the trees. You may move one space.', 'Core'),
    (48, 'The Streets', '8/8', 'Residential', 'Bridge', 'Scenic', 'You pass Anna Kaslow on the street, and she whirls and grabs your arm. "You!" she hisses. "You''re the one I''ve seen in my vision. Let me teach you (Test LORE)." If you pass, she proves to be more than just a simple fortune-teller; you gain one spell. If you fail, you dismiss her ravings as chicanery or dementia.', 'Respectable, elderly Carl Sanford stands at the edge of the bridge with two burly men in bespoke suits. They seem to be watching something in the water, until they turn away as if satisfied. As they pass you, Sanford slips a few bills into your hand. "You didn''t see us here," he says. You gain $2.', 'A basket of fruit stands by the side of the road, with a sign reading "Honor system. Apples $1 per pear." The basket contains both apples and pears. You may eat the fruit to recover two health, and you may spend $1 to pay for it. If you eat without paying, you feel guilty all day; you become CURSED.', 'Core')
);

--  Add Encounter Cards for Special Archive Cards to encounter_card

INSERT INTO encounter_card (id, neighborhood, number, location1, location2, location3, location1Text, location2Text, location3Text, gameSet)
SELECT * FROM (VALUES
    (49, 'Downtown', 'Archive13', 'Arkham Asylum', 'Independence Square', 'La Bella Luna', 'Charles Badoe has an unexpected opening in his schedule. You may spend $1 to recover three sanity. The opening is because one of his patients has escaped...or been set free. Spawn the set-aside "Wolf-Man" Drew monster engaged with you and return this card to the archive.', 'The wagons and stalls of the square''s occasional market are packing up and preparing to leave. You may buy one CURIO item from the display. Soon, you discover why they are leaving. Spawn the set-aside "Wolf-Man" Dean monster engaged with you and return this card to the archive.', 'The high-stakes poker game seems more tense than usual (Test OBSERVATION). If you pass, you exploit the unease the other players feel; you gain $3. Whether you pass or not, a growling man leaps at you outside; spawn the set-aside "Wolf-Man" Dean monster engaged with you and return this card to the archive.', 'Core'),
    (50, 'Easttown', 'Archive14', 'Hibb''s Roadhouse', 'Police Station', 'Velma''s Diner', 'Business is booming. You overhear Old Man Hibbard wondering if Officer Cooper will be by to take his usual bribe "or his pound of flesh." Spawn the set-aside Billy Cooper monster at the police station and return this card to the archive.', 'You share your findings with Sheriff Engle (Test INFLUENCE). If you pass, he offers you some "off-the-books" help; you gain one COMMON item. Whether you pass or not, one particular cop was listening intently; spawn the set-aside Billy Cooper monster at the police station and return this card to the archive.', 'You ask for something without any meat. You may spend $1 recover three health. Velma mentions that a police officer had been by earlier to confiscate all her pork, anyway. Spawn the set-aside Billy Cooper monster at the police station and return this card to the archive.', 'Core'),
    (51, 'Rivertown', 'Archive15', 'Black Cave', 'General Store', 'Graveyard', 'Secrets are written on the walls in blood (Test LORE). If you pass, you decipher them--passages from ''Cultes des Goules''; you gain one spell. Whether you pass or not, you find a discarded gravedigger''s shovel; spawn the set-aside Herman Collins monster at the graveyard and return this card to the archive.', 'The store is open for business, but you''re the only customer. You may buy any number of COMMON items from the display. Davy Schoffner mentions that Herman Collins bought out all his meat last week. Spawn the set-aside Herman Collins monster at the graveyard and return this card to the archive.', 'You find a crate marked with a deer''s skull (Test STRENGTH). If you pass, you break it open and find valuables stolen from corpses inside; you gain $3. Whether you pass or not, you spot one someone fleeing from you; spawn the set-aside Herman Collins monster at the graveyard and return this card to the archive.', 'Core'),
    (52, 'Uptown', 'Archive16', 'Hangman''s Hill', 'St. Mary''s Hospital', 'Ye Olde Magick Shoppe', 'Robed figures meet in the cemetery (Test WILLPOWER). If you pass, you find something they leave behind; you gain one COMMON item. Whether you pass or not, you watch as one of them returns to the hospital; spawn the set-aside Ruth Turner monster at St. Mary''s Hospital and return this card to the archive.', 'You finally get the exhausted Nurse Sharon''s attention. You may spend $1 to recover three health. You sneak into the morgue and watch the mortician load a body into an unmarked car. Spawn the set-aside Ruth Turner monster at St. Mary''s Hospital and return this card to the archive.', 'You find a copy of ''Cult des Goules''. Look at the top three spells in the deck. You may spend $3 to gain one of them. Put the rest on the bottom of the deck. You''re not the first person to read that book. Spawn the set-aside Ruth Turner monster at St. Mary''s Hospital and return this card to the archive.', 'Core'),
    (53, 'Southside', 'Archive17', 'Historical Society', 'Ma''s Boarding House', 'South Church', 'The curator seems distracted (Test INFLUENCE). If you pass, you get access to the collection; you gain one CURIO item. Whether you pass or not, historian Alma Hill is watching you with naked contempt; spawn the set-aside Alma Hill monster at the Historical Society and return this card to the archive.', 'Ma''s got a free seat for dinner. You may spend $1 to recover three health. "Ms. Hill keeps a room here," Ma explains, "but she''s been acting oddly these past few weeks. Spends all her time at the museum." Spawn the set-aside Alma Hill monster at the Historical Society and return this card to the archive.', 'There''s another funeral tonight, with a donation box for the family. You may spend $1 to recover three sanity. You notice a suspicious woman in the crowd. She slips out when she sees you. Spawn the set-aside Alma Hill monster at the Historical Society and return this card to the archive.', 'Core')
);

--  Create event_card table

CREATE TABLE IF NOT EXISTS event_card (
    id SERIAL PRIMARY KEY,
    number VARCHAR(255),
    scenario VARCHAR(255),
    neighborhood VARCHAR(255),
    location1 VARCHAR(255),
    location2 VARCHAR(255),
    location3 VARCHAR(255),
    location1Text TEXT,
    location2Text TEXT,
    location3Text TEXT,
    unstableSpace VARCHAR(255),
    gameSet VARCHAR(255)
);

--  Add Event Cards for Feast for Umordhoth to event_card

INSERT INTO event_card (id, number, scenario, neighborhood, location1, location2, location3, location1Text, location2Text, location3Text, unstableSpace, gameSet)
SELECT * FROM (VALUES
    (1, '5/24', 'Feast for Umordhoth', 'Easttown', 'Hibb''s Roadhouse', 'Police Station', 'Velma''s Diner', 'Patrons are upset about grave robberies and are recounting stories of their departed relatives. You gain one clue from your neighborhood. If you buy a few drinks for guests, they begin to share cherished memories that comfort you. You may spend $1 for you or an ally to recover three sanity.', 'A pile of evidence has been confiscated from a ring of grave robbers. You attempt to stealthily acquire their findings (Test OBSERVATION). If you pass, you gain one COMMON item and one clue from your neighborhood. If you fail, you are caught and questioned extensively; you become delayed.', 'The food smells foul but it is surprisingly invigorating. You or an ally recovers two health. You try to identify the source of the smell (Test OBSERVATION). If you pass, the scent is coming from the water pipes; you gain one clue from your neighborhood. If you fail, you can''t find the source and decide to leave.', 'Hibb''s Roadhouse', 'Core')
);
